#pragma once
// Centralized, serialized input-injection boundary.

#include "types.h"
#include "target_platform.h"

#include <cstddef>
#include <cstdint>

namespace injection {

// Marker attached to every INPUT generated by this subsystem. Hook filters must
// compare against this exported value rather than duplicate a literal.
inline constexpr ULONG_PTR kInjectedInputMarker = static_cast<ULONG_PTR>(0x1337BEEF);
inline constexpr unsigned kMaxReleaseAttempts = 2;

// Backend seam. Production uses ::SendInput; tests replace it with a
// deterministic fake so no test binary imports or invokes the real API.
using SendInputBackend = UINT (*)(UINT count, INPUT* inputs, int inputSize);
using DispatchValidator = bool (*)(const void* context) noexcept;

// All functions return exactly the number reported by their final SendInput
// call. A zero return is a real failure; batch functions may return partial.
UINT KeyDown(Key key);
UINT KeyUp(Key key);
UINT KeyDownUp(Key key);
UINT SpaceDown();
UINT SpaceUp();
UINT MouseWheel(int delta);
UINT SpaceDownIf(DispatchValidator validator, const void* context);
UINT SpaceUpIf(DispatchValidator validator, const void* context);
UINT SpaceDownForTarget(const target_platform::TargetIdentity& target);
UINT SpaceUpForTarget(const target_platform::TargetIdentity& target);
UINT KeyDownIf(Key key, DispatchValidator validator, const void* context);
UINT KeyUpIf(Key key, DispatchValidator validator, const void* context);
UINT KeyDownForTarget(Key key, const target_platform::TargetIdentity& target);
UINT KeyUpForTarget(Key key, const target_platform::TargetIdentity& target);
UINT MouseWheelIf(int delta, DispatchValidator validator, const void* context);

// Attempts every tracked release at most kMaxReleaseAttempts times. The return
// value is the number of inputs released, not an invented success count.
UINT ReconcilePendingReleases();
UINT ReconcilePendingReleasesIf(DispatchValidator validator, const void* context);
UINT ReconcilePendingReleasesForTarget(
    const target_platform::TargetIdentity& target);
std::size_t PendingReleaseCount();
std::uint32_t HeldMovementMask();

// Failsafe shutdown release: emits tagged release events for W, S, A, D,
// Space, and Mouse1 even if they were not recorded as down. Failed releases
// remain pending for a later reconciliation.
UINT ShutdownAndRelease();
UINT ShutdownAndReleaseIf(DispatchValidator validator, const void* context);
UINT ShutdownAndReleaseForTarget(
    const target_platform::TargetIdentity& target);

// Test-only control points. They are intentionally explicit and must never be
// used by application startup/runtime code.
void SetSendInputBackendForTesting(SendInputBackend backend);
void ResetForTesting();

} // namespace injection
