@echo off
echo Starting marco_debug.exe...
start "" /B bin\debug\marco_debug.exe
ping 127.0.0.1 -n 3 > nul
echo Running ui_stress.exe...
tests\ui_stress.exe 15
echo Killing marco_debug.exe...
taskkill /F /IM marco_debug.exe
